server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/business_pos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  security:
    filter:
      order: -100 # Make sure the security filter is applied before the actuator filters

logging:
  level:
    org.springframework: INFO
    com.business.pos: DEBUG
    org.hibernate.type.descriptor.sql: TRACE  # Logs SQL parameters
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  token-validity: 28800  # 8 hours in seconds